# Generated by Django 6.0.5 on 2026-05-29 01:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("nombre", models.CharField(db_index=True, max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "categoria_padre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategorias",
                        to="productos.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("nombre", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "precio_base",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "porcentaje_descuento",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("es_destacado", models.BooleanField(db_index=True, default=False)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="productos",
                        to="productos.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Variante",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("nombre", models.CharField(max_length=200)),
                (
                    "sku",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El SKU solo permite letras mayusculas, numeros y guiones (-).",
                                regex="^[A-Z0-9-]+$",
                            )
                        ],
                    ),
                ),
                (
                    "modificador_precio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("inventario", models.PositiveIntegerField(default=0)),
                ("stock_minimo", models.PositiveIntegerField(default=5)),
                ("atributos", models.JSONField(default=dict)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variantes",
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variante",
                "verbose_name_plural": "Variantes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ImagenProducto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("imagen", models.ImageField(upload_to="productos/")),
                ("es_principal", models.BooleanField(default=False)),
                ("orden", models.PositiveIntegerField(default=0)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagen de Producto",
                "verbose_name_plural": "Imagenes de Productos",
                "ordering": ["orden"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("es_principal", True)),
                        fields=("producto", "es_principal"),
                        name="unique_principal_image_per_product",
                    )
                ],
            },
        ),
    ]
