# Generated by Django 6.0.5 on 2026-06-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_alter_producto_precio_base_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="producto",
            constraint=models.UniqueConstraint(
                fields=("nombre", "categoria"), name="unique_nombre_por_categoria"
            ),
        ),
    ]
