# Generated by Django 6.0.5 on 2026-06-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_producto_unique_nombre_por_categoria"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="producto",
            name="unique_nombre_por_categoria",
            constraint=models.UniqueConstraint(
                fields=("nombre", "categoria"),
                name="unique_nombre_por_categoria",
                violation_error_message="Ya existe un producto con este nombre en esta categoría.",
            ),
        ),
    ]
