# Generated by Django 6.0.5 on 2026-06-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0004_alter_producto_unique_nombre_por_categoria"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="categoria",
            constraint=models.UniqueConstraint(
                fields=("nombre", "categoria_padre"),
                name="unique_nombre_por_categoria_padre",
            ),
        ),
    ]
