# Generated by Django 6.0.5 on 2026-06-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0005_agregar_restriccion_unica_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="tasa_iva",
            field=models.CharField(
                choices=[
                    ("10", "10% (tasa general)"),
                    ("5", "5% (tasa reducida)"),
                    ("0", "Exento"),
                ],
                default="10",
                help_text="Tasa de IVA aplicable a este producto. En Paraguay el IVA va incluido dentro del precio final, no se suma aparte.",
                max_length=2,
            ),
        ),
    ]
