# Generated by Django 6.0.5 on 2026-06-06 13:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productos", "0002_alter_producto_precio_base_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Orden",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("esta_activo", models.BooleanField(default=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("processing", "En proceso"),
                            ("shipped", "Enviada"),
                            ("delivered", "Entregada"),
                            ("cancelled", "Cancelada"),
                            ("refunded", "Reembolsada"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "monto_descuento",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "costo_envio",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                (
                    "codigo_cupon",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("notas", models.TextField(blank=True, default="")),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordenes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden",
                "verbose_name_plural": "Ordenes",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="ItemOrden",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("esta_activo", models.BooleanField(default=True)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=0, max_digits=12),
                ),
                ("nombre_producto", models.CharField(max_length=255)),
                ("nombre_variante", models.CharField(max_length=255)),
                (
                    "variante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items_orden",
                        to="productos.variante",
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ordenes.orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Orden",
                "verbose_name_plural": "Items de Orden",
                "ordering": ["fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEstadoOrden",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("esta_activo", models.BooleanField(default=True)),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("processing", "En proceso"),
                            ("shipped", "Enviada"),
                            ("delivered", "Entregada"),
                            ("cancelled", "Cancelada"),
                            ("refunded", "Reembolsada"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("processing", "En proceso"),
                            ("shipped", "Enviada"),
                            ("delivered", "Entregada"),
                            ("cancelled", "Cancelada"),
                            ("refunded", "Reembolsada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("comentario", models.TextField(blank=True, default="")),
                (
                    "cambiado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_estados",
                        to="ordenes.orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Estado",
                "verbose_name_plural": "Historial de Estados",
                "ordering": ["-fecha"],
            },
        ),
        migrations.AddIndex(
            model_name="orden",
            index=models.Index(
                fields=["usuario", "estado"], name="ordenes_ord_usuario_dc864b_idx"
            ),
        ),
    ]
