# Generated by Django 6.0.5 on 2026-06-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordenes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemorden",
            name="tasa_iva",
            field=models.CharField(
                default="10",
                help_text="Tasa de IVA congelada al momento de la compra. Se guarda aquí para que la factura sea consistente aunque la tasa del producto cambie despues.",
                max_length=2,
            ),
        ),
    ]
