# Generated by Django 6.0.5 on 2026-07-02 23:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ordenes", "0002_agregar_tasa_iva_item_orden"),
        ("productos", "0007_endurecer_restricciones_catalogo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="itemorden",
            constraint=models.CheckConstraint(
                condition=models.Q(("cantidad__gt", 0)),
                name="item_orden_cantidad_positiva",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemorden",
            constraint=models.CheckConstraint(
                condition=models.Q(("precio_unitario__gte", 0)),
                name="item_orden_precio_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="orden",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)),
                name="orden_subtotal_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="orden",
            constraint=models.CheckConstraint(
                condition=models.Q(("monto_descuento__gte", 0)),
                name="orden_descuento_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="orden",
            constraint=models.CheckConstraint(
                condition=models.Q(("costo_envio__gte", 0)),
                name="orden_envio_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="orden",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", 0)), name="orden_total_no_negativo"
            ),
        ),
    ]
