# Generated by Django 6.0.5 on 2026-06-15 21:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("productos", "0005_agregar_restriccion_unica_categoria"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resena",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("esta_activo", models.BooleanField(default=True)),
                (
                    "calificacion",
                    models.PositiveSmallIntegerField(
                        help_text="Calificacion de 1 a 5 estrellas.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Titulo opcional de la reseña.",
                        max_length=200,
                    ),
                ),
                (
                    "comentario",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comentario detallado del producto.",
                    ),
                ),
                (
                    "es_verificada",
                    models.BooleanField(
                        default=False,
                        help_text="True si el usuario compro el producto antes de reseñar.",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resenas",
                        to="productos.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resenas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reseña",
                "verbose_name_plural": "Reseñas",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["producto", "esta_activo"],
                        name="idx_resenas_producto_activo",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "producto"),
                        name="unique_resena_por_usuario_producto",
                    )
                ],
            },
        ),
    ]
