# Generated by Django 6.0.5 on 2026-07-03 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0007_endurecer_restricciones_catalogo"),
        ("resenas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="resena",
            constraint=models.CheckConstraint(
                condition=models.Q(("calificacion__gte", 1), ("calificacion__lte", 5)),
                name="resena_calificacion_entre_1_y_5",
            ),
        ),
    ]
