# Generated by Django 6.0.5 on 2026-06-10 23:00

import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("esta_activo", models.BooleanField(default=True)),
                (
                    "codigo",
                    models.CharField(
                        db_index=True,
                        help_text="Código único del cupón. Se normaliza a mayúsculas.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Descripción interna del cupón para el equipo.",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("porcentaje", "Porcentaje (%)"),
                            ("monto_fijo", "Monto fijo (Gs.)"),
                        ],
                        default="porcentaje",
                        help_text="Tipo de descuento: porcentaje o monto fijo.",
                        max_length=20,
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor del descuento. Si tipo=PORCENTAJE: valor entre 0 y 100. Si tipo=MONTO_FIJO: monto en Guaraníes.",
                        max_digits=12,
                    ),
                ),
                (
                    "monto_minimo",
                    models.DecimalField(
                        decimal_places=0,
                        default=Decimal("0"),
                        help_text="Monto mínimo de la orden para aplicar el cupón en Gs.",
                        max_digits=12,
                    ),
                ),
                (
                    "limite_usos",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Cantidad máxima de usos. Null = sin límite.",
                        null=True,
                    ),
                ),
                (
                    "usos_actuales",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cantidad de veces que fue usado. Se incrementa automáticamente.",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Fecha desde la que el cupón es válido.",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha de vencimiento. Null = no vence.",
                        null=True,
                    ),
                ),
                (
                    "usuarios_permitidos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Usuarios que pueden usar este cupón. Vacío = todos.",
                        related_name="cupones_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cupón",
                "verbose_name_plural": "Cupones",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
