# Generated by Django 6.0.5 on 2026-07-03 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cupones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cupon",
            constraint=models.CheckConstraint(
                condition=models.Q(("valor__gt", 0)), name="cupon_valor_positivo"
            ),
        ),
        migrations.AddConstraint(
            model_name="cupon",
            constraint=models.CheckConstraint(
                condition=models.Q(("monto_minimo__gte", 0)),
                name="cupon_monto_minimo_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="cupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("limite_usos__isnull", True),
                    ("limite_usos__gt", 0),
                    _connector="OR",
                ),
                name="cupon_limite_usos_positivo_o_nulo",
            ),
        ),
        migrations.AddConstraint(
            model_name="cupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tipo", "monto_fijo"), ("valor__lte", 100), _connector="OR"
                ),
                name="cupon_porcentaje_maximo_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="cupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("fecha_vencimiento__isnull", True),
                    ("fecha_vencimiento__gt", models.F("fecha_inicio")),
                    _connector="OR",
                ),
                name="cupon_vencimiento_posterior_inicio",
            ),
        ),
    ]
