# Generated by Django 6.0.5 on 2026-06-20 20:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("esta_activo", models.BooleanField(default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("orden_confirmada", "Orden confirmada"),
                            ("orden_cancelada", "Orden cancelada"),
                            ("pago_aprobado", "Pago aprobado"),
                            ("pago_rechazado", "Pago rechazado"),
                            ("resena_recibida", "Reseña recibida"),
                            ("sistema", "Notificación del sistema"),
                        ],
                        default="sistema",
                        max_length=30,
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título corto de la notificación.", max_length=200
                    ),
                ),
                (
                    "mensaje",
                    models.TextField(
                        help_text="Contenido detallado de la notificación."
                    ),
                ),
                (
                    "leida",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="True una vez que el usuario la marcó como leída.",
                    ),
                ),
                ("fecha_leida", models.DateTimeField(blank=True, null=True)),
                (
                    "referencia_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="UUID del objeto relacionado (orden, pago, reseña).",
                        max_length=64,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificación",
                "verbose_name_plural": "Notificaciones",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "leida"],
                        name="notificacio_usuario_2c9179_idx",
                    )
                ],
            },
        ),
    ]
