# Generated by Django 6.0.5 on 2026-06-07 00:12

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ordenes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("esta_activo", models.BooleanField(default=True)),
                (
                    "pasarela",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("mercado_pago", "Mercado Pago"),
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia Bancaria"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("approved", "Aprobado"),
                            ("rejected", "Rechazado"),
                            ("refunded", "Reembolsado"),
                            ("cancelled", "Cancelado"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Monto del pago en Guaranies.",
                        max_digits=12,
                    ),
                ),
                (
                    "id_transaccion",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ID de la transaccion en la pasarela de pago.",
                        max_length=255,
                    ),
                ),
                (
                    "respuesta_pasarela",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Respuesta completa de la pasarela para auditoria.",
                    ),
                ),
                (
                    "fecha_procesado",
                    models.DateTimeField(
                        blank=True,
                        help_text="Fecha en que la pasarela proceso el pago.",
                        null=True,
                    ),
                ),
                (
                    "orden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="ordenes.orden",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago",
                "verbose_name_plural": "Pagos",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(
                        fields=["orden", "estado"], name="pagos_pago_orden_i_511d0f_idx"
                    )
                ],
            },
        ),
    ]
