# Generated by Django 6.0.5 on 2026-07-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pagos", "0002_restricciones_integridad_pagos"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="pago",
            new_name="pagos_pago_pasarel_722d08_idx",
            old_name="pagos_pago_pasarel_2e44f7_idx",
        ),
    ]
