# Generated by Django 6.0.5 on 2026-07-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pagos",
            "0003_rename_pagos_pago_pasarel_2e44f7_idx_pagos_pago_pasarel_722d08_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pago",
            name="comprobante",
            field=models.FileField(
                blank=True,
                help_text="Comprobante de transferencia subido por el cliente (imagen o PDF). Se usa FileField en lugar de ImageField porque tambien debe aceptar PDF, que ImageField rechazaria.",
                null=True,
                upload_to="comprobantes/",
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="observacion_cliente",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Comentario opcional del cliente sobre la transferencia realizada.",
            ),
        ),
        migrations.AddField(
            model_name="pago",
            name="referencia_cliente",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Numero de referencia u operacion que el cliente indica al transferir.",
                max_length=100,
            ),
        ),
    ]
