# Generated by Django 6.0.5 on 2026-06-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                help_text="Direccion de correo unica del usuario.",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
